# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created: Sat Oct 26 1:20:00 1985
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 260)
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 580, 210))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_choose_directory = QtGui.QLabel(self.frame)
        self.label_choose_directory.setGeometry(QtCore.QRect(10, 10, 80, 20))
        self.label_choose_directory.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_choose_directory.setObjectName("label_choose_directory")
        self.lineEdit_choose_directory = QtGui.QLineEdit(self.frame)
        self.lineEdit_choose_directory.setGeometry(QtCore.QRect(100, 10, 260, 20))
        self.lineEdit_choose_directory.setObjectName("lineEdit_choose_directory")
        self.toolButton_choose_directory = QtGui.QToolButton(self.frame)
        self.toolButton_choose_directory.setGeometry(QtCore.QRect(370, 10, 50, 20))
        self.toolButton_choose_directory.setObjectName("toolButton_choose_directory")
        self.label_search_word = QtGui.QLabel(self.frame)
        self.label_search_word.setGeometry(QtCore.QRect(10, 45, 80, 20))
        self.label_search_word.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_search_word.setObjectName("label_search_word")
        self.lineEdit_search_word = QtGui.QLineEdit(self.frame)
        self.lineEdit_search_word.setGeometry(QtCore.QRect(100, 40, 320, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_search_word.setFont(font)
        self.lineEdit_search_word.setText("")
        self.lineEdit_search_word.setObjectName("lineEdit_search_word")
        self.label_replace_word = QtGui.QLabel(self.frame)
        self.label_replace_word.setGeometry(QtCore.QRect(10, 85, 80, 20))
        self.label_replace_word.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_replace_word.setObjectName("label_replace_word")
        self.lineEdit_replace_word = QtGui.QLineEdit(self.frame)
        self.lineEdit_replace_word.setGeometry(QtCore.QRect(100, 80, 320, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_replace_word.setFont(font)
        self.lineEdit_replace_word.setObjectName("lineEdit_replace_word")
        self.label_extension = QtGui.QLabel(self.frame)
        self.label_extension.setGeometry(QtCore.QRect(10, 120, 80, 20))
        self.label_extension.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_extension.setObjectName("label_extension")
        self.lineEdit_extension = QtGui.QLineEdit(self.frame)
        self.lineEdit_extension.setGeometry(QtCore.QRect(100, 120, 80, 20))
        self.lineEdit_extension.setObjectName("lineEdit_extension")
        self.label_suffix = QtGui.QLabel(self.frame)
        self.label_suffix.setGeometry(QtCore.QRect(10, 150, 80, 20))
        self.label_suffix.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_suffix.setObjectName("label_suffix")
        self.lineEdit_suffix = QtGui.QLineEdit(self.frame)
        self.lineEdit_suffix.setGeometry(QtCore.QRect(100, 150, 80, 20))
        self.lineEdit_suffix.setObjectName("lineEdit_suffix")
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setGeometry(QtCore.QRect(190, 120, 110, 50))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_search = QtGui.QRadioButton(self.groupBox)
        self.radioButton_search.setGeometry(QtCore.QRect(10, 5, 90, 20))
        self.radioButton_search.setObjectName("radioButton_search")
        self.radioButton_regex = QtGui.QRadioButton(self.groupBox)
        self.radioButton_regex.setGeometry(QtCore.QRect(10, 25, 90, 20))
        self.radioButton_regex.setObjectName("radioButton_regex")
        self.pushButton_execute = QtGui.QPushButton(self.frame)
        self.pushButton_execute.setGeometry(QtCore.QRect(310, 120, 110, 50))
        self.pushButton_execute.setObjectName("pushButton_execute")
        self.listWidget_show_dst_files = QtGui.QListWidget(self.frame)
        self.listWidget_show_dst_files.setGeometry(QtCore.QRect(430, 10, 140, 190))
        self.listWidget_show_dst_files.setObjectName("listWidget_show_dst_files")
        self.progressBar = QtGui.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(10, 180, 410, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_notification = QtGui.QLabel(Form)
        self.label_notification.setGeometry(QtCore.QRect(10, 230, 580, 20))
        self.label_notification.setObjectName("label_notification")
        self.label_choose_directory.setBuddy(self.lineEdit_choose_directory)
        self.label_search_word.setBuddy(self.lineEdit_search_word)
        self.label_replace_word.setBuddy(self.lineEdit_replace_word)
        self.label_extension.setBuddy(self.lineEdit_extension)
        self.label_suffix.setBuddy(self.lineEdit_suffix)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_choose_directory, self.toolButton_choose_directory)
        Form.setTabOrder(self.toolButton_choose_directory, self.lineEdit_search_word)
        Form.setTabOrder(self.lineEdit_search_word, self.lineEdit_replace_word)
        Form.setTabOrder(self.lineEdit_replace_word, self.lineEdit_extension)
        Form.setTabOrder(self.lineEdit_extension, self.lineEdit_suffix)
        Form.setTabOrder(self.lineEdit_suffix, self.radioButton_search)
        Form.setTabOrder(self.radioButton_search, self.radioButton_regex)
        Form.setTabOrder(self.radioButton_regex, self.pushButton_execute)
        Form.setTabOrder(self.pushButton_execute, self.listWidget_show_dst_files)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_choose_directory.setText(QtGui.QApplication.translate("Form", "対象フォルダ(&D):", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_choose_directory.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_search_word.setText(QtGui.QApplication.translate("Form", "検索語句(&S):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_replace_word.setText(QtGui.QApplication.translate("Form", "置換語句(&R):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_extension.setText(QtGui.QApplication.translate("Form", "拡張子(&X):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_suffix.setText(QtGui.QApplication.translate("Form", "接尾辞(&F):", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_search.setText(QtGui.QApplication.translate("Form", "通常検索(&H)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_regex.setText(QtGui.QApplication.translate("Form", "正規表現(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_execute.setText(QtGui.QApplication.translate("Form", "置き換える(&P)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_notification.setText(QtGui.QApplication.translate("Form", "すべての項目を入力してください。", None, QtGui.QApplication.UnicodeUTF8))

